new changes

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -85,6 +85,14 @@ jobs:
       - uses: actions/checkout@v4
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
+      - name: Check secrets
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+            echo "❌ Docker secrets are missing!"
+            exit 1
+          else
+            echo "✅ Docker secrets are set."
+          fi
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -104,6 +112,14 @@ jobs:
       - uses: actions/checkout@v4
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
+      - name: Check secrets
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+            echo "❌ Docker secrets are missing!"
+            exit 1
+          else
+            echo "✅ Docker secrets are set."
+          fi
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
